// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQTxeh3Vdy63zENhDIZJHUuQ1njYdLIZ0',
    appId: '1:837777966975:web:cba2eb62c8dfe0da49bc4a',
    messagingSenderId: '837777966975',
    projectId: 'flutter-demo-auth-4bb17',
    authDomain: 'flutter-demo-auth-4bb17.firebaseapp.com',
    storageBucket: 'flutter-demo-auth-4bb17.appspot.com',
    measurementId: 'G-TZKVZCVFVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsiDwSJDGX2SaRQlSQnqgNuicU7N9gHo',
    appId: '1:837777966975:android:ae0c232ba9a5dd4d49bc4a',
    messagingSenderId: '837777966975',
    projectId: 'flutter-demo-auth-4bb17',
    storageBucket: 'flutter-demo-auth-4bb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79gM1tokGG1-a_Z05r1GfqdyR4lPx8O8',
    appId: '1:837777966975:ios:f421ebab59779b0749bc4a',
    messagingSenderId: '837777966975',
    projectId: 'flutter-demo-auth-4bb17',
    storageBucket: 'flutter-demo-auth-4bb17.appspot.com',
    iosClientId: '837777966975-hegq88i725ev5ec4994s6rg98iikmv4i.apps.googleusercontent.com',
    iosBundleId: 'com.mbsoft.flutter.firebaseAuth',
  );
}
